Traceback (most recent call last):
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
table = learn_naive_model(train)
def plot_table_for_target(table, target):
    source_for_is, scores = zip(*[item for item in sorted(table.items()) if item[0][1] == target])
    util.plot_bar_graph(scores, source_for_is, rotation=45, align='center')
plot_table_for_target(table, "is")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [6][0m, in [0;36m<cell line: 5>[0;34m()[0m
[1;32m      3[0m     source_for_is, scores [38;5;241m=[39m [38;5;28mzip[39m([38;5;241m*[39m[item [38;5;28;01mfor[39;00m item [38;5;129;01min[39;00m [38;5;28msorted[39m(table[38;5;241m.[39mitems()) [38;5;28;01mif[39;00m item[[38;5;241m0[39m][[38;5;241m1[39m] [38;5;241m==[39m target])
[1;32m      4[0m     util[38;5;241m.[39mplot_bar_graph(scores, source_for_is, rotation[38;5;241m=[39m[38;5;241m45[39m, align[38;5;241m=[39m[38;5;124m'[39m[38;5;124mcenter[39m[38;5;124m'[39m)
[0;32m----> 5[0m [43mplot_table_for_target[49m[43m([49m[43mtable[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mis[39;49m[38;5;124;43m"[39;49m[43m)[49m

Input [0;32mIn [6][0m, in [0;36mplot_table_for_target[0;34m(table, target)[0m
[1;32m      2[0m [38;5;28;01mdef[39;00m [38;5;21mplot_table_for_target[39m(table, target):
[1;32m      3[0m     source_for_is, scores [38;5;241m=[39m [38;5;28mzip[39m([38;5;241m*[39m[item [38;5;28;01mfor[39;00m item [38;5;129;01min[39;00m [38;5;28msorted[39m(table[38;5;241m.[39mitems()) [38;5;28;01mif[39;00m item[[38;5;241m0[39m][[38;5;241m1[39m] [38;5;241m==[39m target])
[0;32m----> 4[0m     [43mutil[49m[38;5;241m.[39mplot_bar_graph(scores, source_for_is, rotation[38;5;241m=[39m[38;5;241m45[39m, align[38;5;241m=[39m[38;5;124m'[39m[38;5;124mcenter[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'util' is not defined
NameError: name 'util' is not defined

