Traceback (most recent call last):
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/knf792/miniconda3/envs/nlp-course/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
theta1 = create_theta(0.3, 0.7, 0.0, 0.3, 0.7, 1.0, 0.0, 0.0)
theta2 = create_theta(0.3, 0.7, 1.0, 0.0, 0.0, 0.0, 0.3, 0.7)

em.plot_1D(lambda theta: marginal_ll(dataset, theta), theta1, theta2, ylim=[-8.5,-5.5])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [5][0m, in [0;36m<cell line: 4>[0;34m()[0m
[1;32m      1[0m theta1 [38;5;241m=[39m create_theta([38;5;241m0.3[39m, [38;5;241m0.7[39m, [38;5;241m0.0[39m, [38;5;241m0.3[39m, [38;5;241m0.7[39m, [38;5;241m1.0[39m, [38;5;241m0.0[39m, [38;5;241m0.0[39m)
[1;32m      2[0m theta2 [38;5;241m=[39m create_theta([38;5;241m0.3[39m, [38;5;241m0.7[39m, [38;5;241m1.0[39m, [38;5;241m0.0[39m, [38;5;241m0.0[39m, [38;5;241m0.0[39m, [38;5;241m0.3[39m, [38;5;241m0.7[39m)
[0;32m----> 4[0m [43mem[49m[38;5;241m.[39mplot_1D([38;5;28;01mlambda[39;00m theta: marginal_ll(dataset, theta), theta1, theta2, ylim[38;5;241m=[39m[[38;5;241m-[39m[38;5;241m8.5[39m,[38;5;241m-[39m[38;5;241m5.5[39m])

[0;31mNameError[0m: name 'em' is not defined
NameError: name 'em' is not defined

